name: Tests

on:
  pull_request:
jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Install Dependencies
        run: npm install
      - name: Check types
        run: npm run check
